version: 0.2

env:
  variables:
    ECR_REPOSITORY: '671939990958.dkr.ecr.ap-south-1.amazonaws.com/cd-demo'
    COMMIT_HASH: $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7) # Shorten the commit hash

phases:
  install:
    commands:
      - echo Installing project dependencies...
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY
      - echo Pulling the latest Docker image...
      - docker-compose pull app
  build:
    commands:
      - echo Build started on `date`
      - echo Running Docker containers...
      - docker-compose up -d
      - echo Running acceptance tests...
      - npm run test:acceptance
