version: 0.2

env:
  variables:
    ECR_REPOSITORY: '671939990958.dkr.ecr.ap-south-1.amazonaws.com/cd-demo'
    COMMIT_HASH: 'latest'
    S3_BUCKET: 'codepipeline-ap-south-1-751168068033' # Update this with your S3 bucket name
    MICROSERVICE_NAME: 'MicroserviceBackendA' # Update this with your microservice name

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running unit tests..."
      - npm run test:unit
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY
      - COMMIT_HASH=$(bash -c "echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7")

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPOSITORY:$COMMIT_HASH .
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPOSITORY:$COMMIT_HASH

  post_build:
    commands:
      - echo "Storing Docker image tag in Parameter Store..."
      - aws ssm put-parameter --name "/environments/acceptance/MicroserviceBackendA/version" --value "$COMMIT_HASH" --type "String" --overwrite
      - echo "Uploading trigger file to S3..."
      - echo "$MICROSERVICE_NAME-$COMMIT_HASH" > trigger.txt
      - aws s3 cp trigger.txt s3://$S3_BUCKET/$MICROSERVICE_NAME/trigger.txt

artifacts:
  files: 'Dockerfile'
  discard-paths: yes
